
services:
  nginx:
    ports: 
      - "80:80"
    # image: nginx:alpine
    # volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    environment:
      - COMPOSE_PROJECT_NAME