
services:
  nginx:
    ports: 
      - "80:80"
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - COMPOSE_PROJECT_NAME
    command: echo "I'm running ${COMPOSE_PROJECT_NAME}"